import os

Import('env')

penv = env.Clone()
penv.VariantDir(os.path.join(env['OBJDIR'], 'gdl/ces'), '.', duplicate = 0)
penv.SharedLibrary(os.path.join(env['BINDIR'], 'gdl-ces'), Glob(os.path.join(env['OBJDIR'], 'gdl/ces/*.cpp')))
